CREATE DATABASE customer_shopping_db;
USE customer_shopping_db;
SHOW DATABASES;
USE customer_shopping_db;

SELECT * 
FROM customer_shopping
LIMIT 10;

USE customer_shopping_db;

SELECT COUNT(*) AS total_customers
FROM customer_shopping;

SELECT * from customer_shopping limit 20;

DESCRIBE customer_shopping;

ALTER TABLE customer_shopping
CHANGE `Customer ID` customer_id INT,
CHANGE `Age` age INT,
CHANGE `Gender` gender VARCHAR(20),
CHANGE `Item Purchased` item_purchased VARCHAR(100),
CHANGE `Category` category VARCHAR(50),
CHANGE `Purchase Amount (USD)` purchase_amount DECIMAL(10,2),
CHANGE `Location` location VARCHAR(100),
CHANGE `Size` size VARCHAR(20),
CHANGE `Color` color VARCHAR(50),
CHANGE `Season` season VARCHAR(30),
CHANGE `Review Rating` review_rating DECIMAL(3,2),
CHANGE `Subscription Status` subscription_status VARCHAR(20),
CHANGE `Shipping Type` shipping_type VARCHAR(50),
CHANGE `Discount Applied` discount_applied VARCHAR(10),
CHANGE `Promo Code Used` promo_code_used VARCHAR(10),
CHANGE `Previous Purchases` previous_purchases INT,
CHANGE `Payment Method` payment_method VARCHAR(50),
CHANGE `Frequency of Purchases` frequency_of_purchases VARCHAR(50); 

-- Q1 what is the total revenue generated by male vs. female customers?


SELECT gender,
       SUM(`purchase_amount`) AS revenue
FROM customer_shopping
GROUP BY gender;

     
  
-- Q2 which customers used a discount but still spen more than the average purchase amount?

SELECT `customer_id`, `purchase_amount`
FROM customer_shopping
WHERE `discount_applied` = 'Yes'
  AND `purchase_amount` >= (
      SELECT AVG(`purchase_amount`)
      FROM customer_shopping
  );
  
  -- which are the top 5 products with the highest average review rating?
  
  select  item_purchased, AVG(review_rating) as "Average Product Rating"
FROM customer_shopping
group by item_purchased  
order by avg(review_rating) desc
limit 5;
  
  -- Q4 compare the average Purchase Amount's Between Standard and Express Shipping?
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM customer_shopping
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5 Do subscribe customers spend more? compare average spend and total revenue between subscribe and non subscribe?
select subscription_status,
count(customer_id) as total_customer,
round(AVG(purchase_amount),2) as avg_spend,
round(AVG(purchase_amount),2) as total_revenue
from customer_shopping
group by subscription_status
order by total_revenue, avg_spend desc;

-- Q6. which 5 products have the highest percentage of purchases with discounts applied?
 select item_purchased,
 round(SUM(CASE WHEN discount_applied = "yes" THEN 1 ELSE 0 END)/COUNT(*) * 100,2) as discount_rate
 from customer_shopping
 group by item_purchased
 order by discount_rate desc
 limit 5;
 
 -- Q7 segment customer into New, Returning, and Loyal based on their total number of previous purchase and show the count of each segment. 
 with customer_type as (
 select customer_id, previous_purchases,
 CASE
      WHEN previous_purchases = 1 THEN 'New'
      WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
      ELSE 'Loyal'
      END AS customer_segment
from customer_shopping
)
select customer_segment,count(*) as "Number of Customers"
from customer_type
group by customer_segment;



-- Q8 What are the top 3 most purchases products within each category?
WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer_shopping
    GROUP BY category, item_purchased
)

SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Q9 Are customer who are repeat buyers(more than 5 previous purchases ) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer_shopping
where previous_purchases > 5
group by subscription_status;

-- Q10 what is the revenue contribution of each age group?
select age,
sum(purchase_amount) as total_revenue
from customer_shopping
group by age
order by total_revenue desc;

